### ISSUE TITLE
Check/implement Home Assistant integration

### ISSUE THREAD

**Issue by matthias-bs** [matthias-bs/Flora2#1]
https://www.home-assistant.io/integrations/plant

```yaml
# Example configuration.yaml entry
plant:
  "Flower Box":
    sensors:
      moisture: sensor.s6_moisture
      battery: sensor.s6_battery
      temperature: sensor.s6_temperature
      conductivity: sensor.s6_conductivity
      brightness: sensor.s6_brightness
    min_moisture: 20

mqtt:    
  sensor:
    - name: s6_moisture
      state_topic: "flora2o/Sensor6"
      value_template: "{{ value_json.moisture | int }}"
      unit_of_measurement: "%"
    - name: s6_battery
      state_topic: "flora2o/Sensor6"
      value_template: "{{ value_json.battery | int }}"
      unit_of_measurement: "%"
    - name: s6_temperature
      state_topic: "flora2o/Sensor6"
      value_template: "{{ value_json.temperature | float }}"
      unit_of_measurement: "°C" 
    - name: s6_conductivity
      state_topic: "flora2o/Sensor6"
      value_template: "{{ value_json.conductivity | int }}"
      unit_of_measurement: "µS/cm"
    - name: s6_brightness
      state_topic: "flora2o/Sensor6"
      value_template: "{{ value_json.light | int }}"
      unit_of_measurement: "lx"

```

![Image](https://github.com/user-attachments/assets/ad96be82-536d-4806-8e30-5577c973d2ef)
